version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-producto3
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=producto3 
    volumes:
      - mongo-data:/data/db
      #- ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

volumes:
  mongo-data: